# Generated by Django 5.1.7 on 2025-03-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_stufforder_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stufforder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
