# Generated by Django 5.1.7 on 2025-06-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_stufforder_user_alter_stufforder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stufforder',
            name='user',
        ),
    ]
