# Generated by Django 5.1.7 on 2025-06-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_stufforder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stufforder',
            name='user',
        ),
    ]
